apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedNamespace
metadata:
  name: test
  namespace: test
spec:
  placement:
    clusters:
      - name: eks-federated-1.us-east-1
      - name: eks-federated-2.us-west-2
    clusterSelector: {}